//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_C3D_Input : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.c3D_Input_Grip;
            }
        }
        
        public virtual SteamVR_Action_Single Trigger
        {
            get
            {
                return SteamVR_Actions.c3D_Input_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Touchpad
        {
            get
            {
                return SteamVR_Actions.c3D_Input_Touchpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touchpad_Press
        {
            get
            {
                return SteamVR_Actions.c3D_Input_Touchpad_Press;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touchpad_Touch
        {
            get
            {
                return SteamVR_Actions.c3D_Input_Touchpad_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.c3D_Input_Menu;
            }
        }
    }
}
